---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.kpack.io
spec:
  group: kpack.io
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: LatestImage
          type: string
          jsonPath: .status.latestImage
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: LatestImage
          type: string
          jsonPath: .status.latestImage
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
  names:
    kind: ClusterBuilder
    listKind: ClusterBuilderList
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
      - clstbldr
      - clstbldrs
    categories:
      - kpack
  scope: Cluster
