---
apiVersion: build.knative.dev/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: buildpacks-cnb
spec:
  parameters:
  - name: IMAGE
    description: The image you wish to create. For example, "repo/example", or "example.com/repo/image".
  - name: RUN_IMAGE
    description: The run image buildpacks will use as the base for IMAGE.
  - name: BUILDER_IMAGE
    description: The builder image (must include v3 lifecycle and compatible buildpacks).
  - name: USE_CRED_HELPERS
    description: Use Docker credential helpers for Google's GCR, Amazon's ECR, or Microsoft's ACR.
    default: 'false'
  - name: CACHE
    description: The name of the persistent app cache volume
    default: empty-dir
  - name: USER_ID
    description: The user ID of the builder image user
    default: "1000"
  - name: GROUP_ID
    description: The group ID of the builder image user
    default: "1000"

  steps:
  - name: prepare
    image: alpine
    command: ["/bin/sh"]
    args:
    - "-c"
    - >
      chown -R "${USER_ID}:${GROUP_ID}" "/builder/home" &&
      chown -R "${USER_ID}:${GROUP_ID}" /layers &&
      chown -R "${USER_ID}:${GROUP_ID}" /cache &&
      chown -R "${USER_ID}:${GROUP_ID}" /workspace
    imagePullPolicy: Always
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers
    - name: "${CACHE}"
      mountPath: /cache

  - name: detect
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/detector"]
    args:
    - "-app=/workspace"
    - "-group=/layers/group.toml"
    - "-plan=/layers/plan.toml"
    imagePullPolicy: Always
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: restore
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/restorer"]
    args:
    - "-group=/layers/group.toml"
    - "-layers=/layers"
    - "-path=/cache"
    imagePullPolicy: Always
    volumeMounts:
    - name: "${CACHE}"
      mountPath: /cache
    - name: "layers-dir"
      mountPath: /layers

  - name: analyze
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/analyzer"]
    args:
    - "-layers=/layers"
    - "-helpers=${USE_CRED_HELPERS}"
    - "-group=/layers/group.toml"
    - "${IMAGE}"
    imagePullPolicy: Always
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: build
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/builder"]
    args:
    - "-layers=/layers"
    - "-app=/workspace"
    - "-group=/layers/group.toml"
    - "-plan=/layers/plan.toml"
    imagePullPolicy: Always
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: export
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/exporter"]
    args:
    - "-layers=/layers"
    - "-helpers=${USE_CRED_HELPERS}"
    - "-app=/workspace"
    - "-image=${RUN_IMAGE}"
    - "-group=/layers/group.toml"
    - "${IMAGE}"
    imagePullPolicy: Always
    volumeMounts:
    - name: "layers-dir"
      mountPath: /layers

  - name: cache
    image: ${BUILDER_IMAGE}
    command: ["/lifecycle/cacher"]
    args:
    - "-group=/layers/group.toml"
    - "-layers=/layers"
    - "-path=/cache"
    imagePullPolicy: Always
    volumeMounts:
    - name: "${CACHE}"
      mountPath: /cache
    - name: "layers-dir"
      mountPath: /layers

  volumes:
  - name: empty-dir
    emptyDir: {}
  - name: layers-dir
    emptyDir: {}