apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: ".status.latestImage"
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: ".status.latestImage"
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
      conversionReviewVersions: ["v1"]
  names:
    kind: Image
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    - img
    - imgs
    categories:
    - kpack
  scope: Namespaced
