apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Image
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: ".status.latestImage"
