#@data/values
---
controller_image: gcr.io/controller
build_init_image: gcr.io/build-init
rebase_image: gcr.io/rebase
nop_image: gcr.io/pivotal-knative/github.com/knative/build/cmd/nop@sha256:dc7e5e790001c71c2cfb175854dd36e65e0b71c58294b331a519be95bdec4ef4
version: dev